### ISSUE TITLE
Import-Clixml Error when opening Terminal

### ISSUE THREAD

**Issue by Irtiza90** [devblackops/Terminal-Icons#126]
## Current Behavior

I get an error randomly when i open the terminal, it only gives an error at launch.

#### Error Message:
*(yesterday, when i checked i received this error message)*
```
Import-Clixml: Key for dictionary entry is not specified. Line 104, position 7.
InvalidOperation: Index operation failed; the array index evaluated to null.
Import-Clixml: 'Element' is an invalid XmlNodeType.
InvalidOperation: Index operation failed; the array index evaluated to null.
InvalidOperation: Index operation failed; the array index evaluated to null.
```

*(this error i just received)*
```
Import-Clixml: Value for dictionary entry is not specified. Line 109, position 21.
InvalidOperation: Index operation failed; the array index evaluated to null.
InvalidOperation: Index operation failed; the array index evaluated to null.
InvalidOperation: Cannot index into a null array.
InvalidOperation: Cannot index into a null array.
InvalidOperation: You cannot call a method on a null-valued expression.
InvalidOperation: You cannot call a method on a null-valued expression.
```

## Steps to Reproduce (for bugs)
Opening the terminal randomly gives the error, sometimes i see the error, othertimes i don't.

The error doesn't seem to be causing any issues with the terminal, most probably just a visual error.

## Your Environment

OS Version: Windows 10(22H2)
Terminal: Powershell 7.4.1
I'm using ohmyposh and Terminal-Icons powershell modules

**Comment by mattcargile** [comment]
We would want to see the output from the below after the error.
```pwsh
get-error -last 2
```

Additionally, does the same error happen when you load _PowerShell Core_ with no profile? You launch with `pwsh -noprofile`.

Lastly, it is possibly related to https://github.com/devblackops/Terminal-Icons/issues/121.

**Comment by hero3616** [comment]
If you don't mind 1 second delay below profile works for me with a 2x2 split terminal startup with pwsh 7.4.5

```
oh-my-posh init pwsh --config '<your-config>.json' | Invoke-Expression

$WarningPreference = 'SilentlyContinue'
$ErrorActionPreference = 'SilentlyContinue'

Import-Module -Name Terminal-Icons

# set back to default values with a 1 second delay
Start-Sleep -Seconds 1
$WarningPreference = 'Continue'
$ErrorActionPreference = 'Continue'
```

**Comment by techthoughts2** [comment]
Similar error for me:

```powershell
import-module terminal-icons
Import-Clixml: Value for dictionary entry is not specified. Line 603, position 40.
```

Full error:

```powershell
PSMessageDetails      :
Exception             : System.Xml.XmlException: Value for dictionary entry is not specified. Line 603, position 40.
                           at System.Management.Automation.InternalDeserializer.ReadDictionary(ContainerType ct, ConsolidatedString
                        InternalTypeNames)
                           at System.Management.Automation.InternalDeserializer.ReadPSObject()
                           at System.Management.Automation.InternalDeserializer.ReadOneDeserializedObject(String& streamName, Boolean&
                        isKnownPrimitiveType)
                           at System.Management.Automation.InternalDeserializer.ReadOneObject(String& streamName)
                           at System.Management.Automation.InternalDeserializer.ReadDictionary(ContainerType ct, ConsolidatedString
                        InternalTypeNames)
                           at System.Management.Automation.InternalDeserializer.ReadPSObject()
                           at System.Management.Automation.InternalDeserializer.ReadOneDeserializedObject(String& streamName, Boolean&
                        isKnownPrimitiveType)
                           at System.Management.Automation.InternalDeserializer.ReadOneObject(String& streamName)
                           at System.Management.Automation.InternalDeserializer.ReadDictionary(ContainerType ct, ConsolidatedString
                        InternalTypeNames)
                           at System.Management.Automation.InternalDeserializer.ReadPSObject()
                           at System.Management.Automation.InternalDeserializer.ReadOneDeserializedObject(String& streamName, Boolean&
                        isKnownPrimitiveType)
                           at System.Management.Automation.InternalDeserializer.ReadOneObject(String& streamName)
                           at System.Management.Automation.Deserializer.Deserialize(String& streamName)
                           at System.Management.Automation.Deserializer.Deserialize()
                           at Microsoft.PowerShell.Commands.ImportXmlHelper.Import()
                           at Microsoft.PowerShell.Commands.ImportClixmlCommand.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Import-Clixml], XmlException
FullyQualifiedErrorId : System.Xml.XmlException,Microsoft.PowerShell.Commands.ImportClixmlCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Users\jakew\OneDrive\Documents\PowerShell\Modules\terminal-icons\0.11.0\Terminal-Icons.psm1: line
                        3419
                        at <ScriptBlock>, C:\Users\jakew\OneDrive\Documents\PowerShell\Modules\terminal-icons\0.11.0\Terminal-Icons.psm1: line
                        3418
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

When exploring these lines in `Terminal-Icons.psm1`:

```powershell
(Get-ChildItem $userThemePath -Filter '*_icon.xml').ForEach({
    $userIconTheme = Import-CliXml -Path $_.FullName
    $userThemeData.Themes.Icon[$userIconTheme.Name] = $userIconTheme
})
```

I found that `$userIconTheme` tracked back to `$basePath = [Environment]::GetFolderPath('ApplicationData')`.

This location did not contain the expected xml files, thus why this error was occuring.

My workaround to address this for me was:
1. Launch `cmd.exe`
2. Run `pwsh -noprofile`
3. Run `Import-Module terminal-icons`

The above steps caused the module to create a: `AppData\Roaming\powershell\Community\Terminal-Icons` and the module is now able to be imported in Terminal.

**Comment by atrenton** [comment]
The simplest temporary workaround I've found for these `Import-Clixml` cmdlet errors is to delete the `AppData\Roaming\powershell\Community\Terminal-Icons` folder before loading the `Terminal-Icons` module. Here are the relevant lines from my PowerShell profile:
```powershell
# REF: https://stapp.space/few-steps-to-pimp-my-terminal/#my-profile-file
function Import-Module-With-Measure {  
    param ($ModuleName)
    $import = Measure-Command {
        Import-Module $ModuleName
    }
    Write-Host "Loading $ModuleName took $([math]::Round($import.TotalMilliseconds))ms."
}

$terminalIconsFolder = "$env:APPDATA\powershell\Community\Terminal-Icons"
if (Test-Path $terminalIconsFolder){
    Remove-Item $terminalIconsFolder -Recurse
}
Import-Module-With-Measure Terminal-Icons
```

The module automatically recreates this folder when it loads. With my 8th Gen **Intel® Core™ i7-8700 CPU @ 3.20GHz processor**, the module only takes `< 500ms (1/2 second)` to load with this workaround.

**Comment by silverqx** [comment]
This is the full stacktrace obtained using `$Error | Get-Error`, would be good to fix or workaround this:

<details><summary>Details - Terminal Output</summary>
<p>

```pwsh
λ $Error | Get-Error

Exception             :
    Type        : System.Management.Automation.RuntimeException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Index operation failed; the array index evaluated to null.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : NullArrayIndex
        InvocationInfo        :
            ScriptLineNumber : 3416
            OffsetInLine     : 5
            HistoryId        : 1
            ScriptName       : C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Icons.
psm1
            Line             :     $userThemeData.Themes.Icon[$userIconTheme.Name] = $userIconTheme

            Statement        : $userThemeData.Themes.Icon[$userIconTheme.Name] = $userIconTheme
            PositionMessage  : At C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Ico
ns.psm1:3416 char:5
                               +     $userThemeData.Themes.Icon[$userIconTheme.Name] = $userIconTheme
                               +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     : C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0
            PSCommandPath    : C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Icons.
psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.1
1.0\Terminal-Icons.psm1: line 3416
                                at <ScriptBlock>, C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.1
1.0\Terminal-Icons.psm1: line 3414
                                at <ScriptBlock>, C:\Users\<example>\Documents\PowerShell\Microsoft.PowerShell_profi
le.ps1: line 25
                                at <ScriptBlock>, <No file>: line 1
    TargetSite  : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.
CallSite, System.Object, System.Object, System.Object)
    Message     : Index operation failed; the array index evaluated to null.
    Data        : System.Collections.ListDictionaryInternal
    Source      : Anonymously Hosted DynamicMethods Assembly
    HResult     : -2146233087
    StackTrace  :
   at CallSite.Target(Closure, CallSite, Object, Object, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : NullArrayIndex
InvocationInfo        :
    ScriptLineNumber : 3416
    OffsetInLine     : 5
    HistoryId        : 1
    ScriptName       : C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Icons.psm1
    Line             :     $userThemeData.Themes.Icon[$userIconTheme.Name] = $userIconTheme

    Statement        : $userThemeData.Themes.Icon[$userIconTheme.Name] = $userIconTheme
    PositionMessage  : At C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Icons.psm1:
3416 char:5
                       +     $userThemeData.Themes.Icon[$userIconTheme.Name] = $userIconTheme
                       +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0
    PSCommandPath    : C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Icons.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Term
inal-Icons.psm1: line 3416
                        at <ScriptBlock>, C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Term
inal-Icons.psm1: line 3414
                        at <ScriptBlock>, C:\Users\<example>\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:
line 25
                        at <ScriptBlock>, <No file>: line 1
Exception             :
    Type         : System.Xml.XmlException
    LineNumber   : 1156
    LinePosition : 50
    Message      : The 'S' start tag on line 1156 position 22 does not match the end tag of 'En'. Line 1156, position 50.
    TargetSite   :
        Name          : Throw
        DeclaringType : [System.Xml.XmlTextReaderImpl]
        MemberType    : Method
        Module        : System.Private.Xml.dll
    Source       : System.Private.Xml
    HResult      : -2146232000
    StackTrace   :
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlReader.InternalReadContentAsString()
   at System.Xml.XmlReader.ReadElementContentAsString()
   at System.Management.Automation.InternalDeserializer.ReadDecodedElementString(String element)
   at System.Management.Automation.InternalDeserializer.ReadPrimaryKnownType(TypeSerializationInfo pktInfo)
   at System.Management.Automation.InternalDeserializer.ReadOneDeserializedObject(String& streamName, Boolean& isKnownPri
mitiveType)
   at System.Management.Automation.InternalDeserializer.ReadOneObject(String& streamName)
   at System.Management.Automation.InternalDeserializer.ReadDictionary(ContainerType ct, ConsolidatedString InternalTypeN
ames)
   at System.Management.Automation.InternalDeserializer.ReadPSObject()
   at System.Management.Automation.InternalDeserializer.ReadOneDeserializedObject(String& streamName, Boolean& isKnownPri
mitiveType)
   at System.Management.Automation.InternalDeserializer.ReadOneObject(String& streamName)
   at System.Management.Automation.InternalDeserializer.ReadDictionary(ContainerType ct, ConsolidatedString InternalTypeN
ames)
   at System.Management.Automation.InternalDeserializer.ReadPSObject()
   at System.Management.Automation.InternalDeserializer.ReadOneDeserializedObject(String& streamName, Boolean& isKnownPri
mitiveType)
   at System.Management.Automation.InternalDeserializer.ReadOneObject(String& streamName)
   at System.Management.Automation.InternalDeserializer.ReadDictionary(ContainerType ct, ConsolidatedString InternalTypeN
ames)
   at System.Management.Automation.InternalDeserializer.ReadPSObject()
   at System.Management.Automation.InternalDeserializer.ReadOneDeserializedObject(String& streamName, Boolean& isKnownPri
mitiveType)
   at System.Management.Automation.InternalDeserializer.ReadOneObject(String& streamName)
   at System.Management.Automation.Deserializer.Deserialize(String& streamName)
   at System.Management.Automation.Deserializer.Deserialize()
   at Microsoft.PowerShell.Commands.ImportXmlHelper.Import()
   at Microsoft.PowerShell.Commands.ImportClixmlCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Import-Clixml], XmlException
FullyQualifiedErrorId : System.Xml.XmlException,Microsoft.PowerShell.Commands.ImportClixmlCommand
InvocationInfo        :
    MyCommand        : Import-Clixml
    ScriptLineNumber : 3415
    OffsetInLine     : 22
    HistoryId        : 1
    ScriptName       : C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Icons.psm1
    Line             :     $userIconTheme = Import-CliXml -Path $_.FullName

    Statement        : Import-CliXml -Path $_.FullName
    PositionMessage  : At C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Icons.psm1:
3415 char:22
                       +     $userIconTheme = Import-CliXml -Path $_.FullName
                       +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0
    PSCommandPath    : C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Terminal-Icons.psm1
    InvocationName   : Import-CliXml
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Term
inal-Icons.psm1: line 3415
                        at <ScriptBlock>, C:\Users\<example>\Documents\PowerShell\Modules\Terminal-Icons\0.11.0\Term
inal-Icons.psm1: line 3414
                        at <ScriptBlock>, C:\Users\<example>\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:
line 25
                        at <ScriptBlock>, <No file>: line 1
```

</p>
</details>

**Comment by Frulfump** [comment]
I got similar errors on restarts of my shell

>Import-Clixml: 'Element' is an invalid XmlNodeType.
InvalidOperation: Index operation failed; the array index evaluated to null.

>InvalidOperation: Index operation failed; the array index evaluated to null.
InvalidOperation: Index operation failed; the array index evaluated to null.

>Import-Clixml: Unexpected end of file has occurred. The following elements are not closed: S, En, DCT, Obj, En, DCT, Obj, En, DCT, Obj, En, DCT, Obj, Objs. Line 1517, position 46.
InvalidOperation: Index operation failed; the array index evaluated to null.

>Import-Clixml: Name attribute for dictionary key is incorrectly specified. Line 800, position 33.
InvalidOperation: Index operation failed; the array index evaluated to null.
InvalidOperation: Index operation failed; the array index evaluated to null.

And the issue was caused by me having only set `[System.Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()` to workaround issues with piping UTF-8 content to ripgrep and the solution was to also set the input encoding to UTF-8 (without BOM)
`[System.Console]::InputEncoding = [System.Console]::OutputEncoding` (since output was already set above).

Followed https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#pipe-non-ascii-windows
ASCII default encoding issues on Windows for strings to external programs https://github.com/PowerShell/PowerShell/issues/7233

**Comment by silverqx** [comment]
It really solves the problem? Setting this? `[System.Console]::InputEncoding = [System.Console]::OutputEncoding`

**Comment by Frulfump** [comment]
Yeah the problems I were having at least given that I set `[System.Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()` first

**Comment by silverqx** [comment]
thx, but I dont understand one thing, the problem is in UTF-8 BOM? like that BOM char?

cause the default encoding in the latest pwsh is like this (for both Output and also `InputEncoding`):

```shell
PS H:\Downloads\_tmp\_tt> [System.Console]::OutputEncoding

Preamble          : 
BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : False
CodePage          : 65001
```

**Comment by Frulfump** [comment]
It works for me with either the BOM or without but according to this issue https://github.com/PowerShell/PowerShell/issues/7233 the default encoding is ASCII on Windows and UTF-8 on Linux and MacOS for strings from external programs.

>However, because the console-window shortcut file / taskbar entry still defaults to the OEM code page implied by the legacy system locale (e.g. 437 on US-English systems), it misinterprets strings from external programs; e.g., with Node.js installed:) 

and I had issues with piping content to ripgrep without doing the above What's your InputEncoding, I have the same OutputEncoding as you and my InputEncoding is the same as well in a `pwsh --no-profile`? I use pwsh version 7.5.1 are you on the same?

Here's my $PROFILE

```
# Set the output encoding to UTF-8 (without BOM) (fixes issues when piping to other programs (e.g ripgrep))
[System.Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()

# Set the input encoding to UTF-8 (without BOM) for consistent encoding (Import-Module would otherwise fail with strange errors)
[System.Console]::InputEncoding = [System.Console]::OutputEncoding

# Set the prompt to use oh-my-posh
oh-my-posh init pwsh --config "~\frulfump.omp.json" | Invoke-Expression

Import-Module -Name Terminal-Icons
```

So If I had just set the OutputEncoding it would fail with the errors I wrote about above.
And piping non ASCII to ripgrep would give me back garbled text like in this discussion https://github.com/BurntSushi/ripgrep/discussions/2511 but I had issues with example content

```text
│       ├── minimatch@9.0.5`
```
gave me

```text
85:Γöé       Γö£ΓöÇΓöÇ minimatch@9.0.5
```

**Comment by silverqx** [comment]
aah I see, I have enable `UTF-8` support in Window regional settings, that why I have by default UTF-8

I dont know though if am still experiencing this Error, if I do manually eg.:

```pwsh
pwsh -NoProfile
import-module terminal-icons
```

then I cant reproduce it, but am at 100% sure I have UTF-8 even before, when I saw that error. its not a big deal though, bugs are everywhere and we live with them somehow 🤭

**Comment by hero3616** [comment]
> The simplest temporary workaround I've found for these `Import-Clixml` cmdlet errors is to delete the `AppData\Roaming\powershell\Community\Terminal-Icons` folder before loading the `Terminal-Icons` module. Here are the relevant lines from my PowerShell profile:
> 
> # REF: https://stapp.space/few-steps-to-pimp-my-terminal/#my-profile-file
> function Import-Module-With-Measure {  
>     param ($ModuleName)
>     $import = Measure-Command {
>         Import-Module $ModuleName
>     }
>     Write-Host "Loading $ModuleName took $([math]::Round($import.TotalMilliseconds))ms."
> }
> 
> $terminalIconsFolder = "$env:APPDATA\powershell\Community\Terminal-Icons"
> if (Test-Path $terminalIconsFolder){
>     Remove-Item $terminalIconsFolder -Recurse
> }
> Import-Module-With-Measure Terminal-Icons
> The module automatically recreates this folder when it loads. With my 8th Gen **Intel® Core™ i7-8700 CPU @ 3.20GHz processor**, the module only takes `< 500ms (1/2 second)` to load with this workaround.

This didn't work for me. I still get errors when I run 2x2 or 2x3 split terminal using:

"startupActions": "split-pane -V; move-focus left; split-pane -H; move-focus right; split-pane -H; move-focus up; move-focus left"

(I didn't try with single pane)

The only 100% working solution is still:

```powershell
oh-my-posh init pwsh --config 'C:\Users\tutsiki.yancek\AppData\Local\Programs\oh-my-posh\themes\ohmyposhv3-v3.json' | Invoke-Expression

$WarningPreference = 'SilentlyContinue'
$ErrorActionPreference = 'SilentlyContinue'

Import-Module -Name Terminal-Icons

# set back to default values with a 1 second delay
Start-Sleep -Seconds 1
$WarningPreference = 'Continue'
$ErrorActionPreference = 'Continue'
```

<img width="1490" height="1156" alt="Image" src="https://github.com/user-attachments/assets/2185791f-c310-43f1-8482-c30df427b8f0" />
